apiVersion: v1
kind: Service
metadata:
  name: ip-manager
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ip-manager
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
