server {
    listen 8080;
    server_name _;

    location FRONTEND_BASE_PATH {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ FRONTEND_BASE_PATH/index.html;
    }

    location = FRONTEND_BASE_PATH_NO_SLASH {
        return 301 FRONTEND_BASE_PATH;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
